"""
app.py — FastAPI server for PromptBridge

PromptBridge turns a user's vague request into a fully structured,
domain-aware optimized prompt ready to paste into any AI model.

Endpoints:
  POST /generate-prompt — main pipeline: vague request → optimized prompt
  POST /chat            — alias for /generate-prompt (backward compat)
  POST /session/clear   — clear memory for a session
  GET  /session/{id}    — get session history
  GET  /health          — health check
  GET  /cache/stats     — cache hit/miss statistics
  POST /cache/flush     — flush all cached entries

Run:
  uvicorn app:app --host 0.0.0.0 --port 8080 --reload
  Docs: http://localhost:8080/docs
"""

import os
from contextlib import asynccontextmanager
from dotenv import load_dotenv
# pyrefly: ignore [missing-import]
from fastapi import FastAPI, HTTPException
# pyrefly: ignore [missing-import]
from fastapi.middleware.cors import CORSMiddleware
# pyrefly: ignore [missing-import]
from pydantic import BaseModel
from pipeline import PromptBridgePipeline

load_dotenv(dotenv_path="../.env")

# ── Global pipeline instance (loaded once at startup) ─────────────────────────
pipelines: dict[str, PromptBridgePipeline] = {}

def get_pipeline(session_id: str) -> PromptBridgePipeline:
    """Get or create a pipeline for this session."""
    if session_id not in pipelines:
        pipelines[session_id] = PromptBridgePipeline(session_id=session_id)
    return pipelines[session_id]

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Pre-load default pipeline on startup
    get_pipeline("default")
    yield
    pipelines.clear()

app = FastAPI(
    title="PromptBridge RAG API",
    description="Hybrid RAG pipeline with memory",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Schemas ───────────────────────────────────────────────────────────────────
class PromptRequest(BaseModel):
    query:      str           # user's vague / incomplete request
    session_id: str = "default"

class PromptResponse(BaseModel):
    query:            str     # original user request
    optimized_prompt: str     # the structured prompt generated by the pipeline
    intent:           str     # classified intent (code / ml / research / ...)
    domain:           str     # detected domain (Computer Vision / NLP / ...)
    sources:          list[str]
    latency_s:        float
    chunks:           list[dict] = []
    cached:           bool = False

class ClearRequest(BaseModel):
    session_id: str = "default"

# ── Helper ────────────────────────────────────────────────────────────────────
def _build_response(result: dict) -> PromptResponse:
    """Map pipeline result dict → PromptResponse."""
    return PromptResponse(
        query             = result["query"],
        optimized_prompt  = result["optimized_prompt"],
        intent            = result["intent"],
        domain            = result.get("domain", "General"),
        sources           = result["sources"],
        latency_s         = result["latency_s"],
        cached            = result.get("cached", False),
        chunks            = [
            {
                "text":         c["text"][:200],
                "source":       c.get("source", ""),
                "doc_title":    c.get("doc_title", ""),
                "rerank_score": c.get("rerank_score", 0),
            }
            for c in result.get("chunks", [])
        ],
    )

# ── Endpoints ─────────────────────────────────────────────────────────────────
@app.post("/generate-prompt", response_model=PromptResponse)
async def generate_prompt(req: PromptRequest):
    """Main endpoint — transforms a vague user request into an optimized prompt."""
    if not req.query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty")

    pipeline = get_pipeline(req.session_id)
    result   = pipeline.query(req.query, verbose=False)
    return _build_response(result)


@app.post("/chat", response_model=PromptResponse)
async def chat(req: PromptRequest):
    """Alias for /generate-prompt (backward compatibility)."""
    return await generate_prompt(req)

@app.post("/session/clear")
async def clear_session(req: ClearRequest):
    if req.session_id in pipelines:
        pipelines[req.session_id].memory.clear_session()
    return {"status": "cleared", "session_id": req.session_id}

@app.get("/session/{session_id}")
async def get_session(session_id: str):
    pipeline = get_pipeline(session_id)
    return {
        "session_id": session_id,
        "turns":      pipeline.memory.turn_count,
        "history":    pipeline.memory.get_history()[-10:],  # last 10 messages
    }

@app.get("/health")
async def health():
    return {
        "status":          "ok",
        "active_sessions": len(pipelines),
        "model":           "openai/gpt-oss-20b",
    }


@app.get("/cache/stats")
async def cache_stats():
    """Return cache hit/miss stats for the default pipeline."""
    pipeline = get_pipeline("default")
    return pipeline.cache.stats


@app.post("/cache/flush")
async def cache_flush():
    """Flush all cached embeddings, chunks, and answers."""
    pipeline = get_pipeline("default")
    pipeline.cache.flush_all()
    return {"status": "flushed"}